language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get install libavahi-compat-libdnssd-dev
  - npm install -g grunt-cli
  - npm install -g bower
  - gem install sass
install:
  - npm install
  - bower install
